### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by powerjg** [darchr/gem5art#1]
- Intro: 
  - [x] Explain the motivation behind gem5art
  - [x] Talk about main parts a bit
  - [x] Talk about how to install
- Artifacts
  - [x] What this is
  - [x] How to use
  - [x] Examples
  - [x] Search the DB
  - [x] Use something from the DB
- Run
  - [x] What it is
  - [x] How to use
  - [x] What are the assumptions on the config/run script?
  - [x] Simple example in SE mode
  - [x] Simple example in FS mode
  - [x] Show how to search the DB with `getRuns`
- Tasks
  - [x] What it is
  - [x] How to start a server and launch jobs
- Disk images
  - [x] Basically what Hoa has already written
- Tutorials: Full examples from start to finish
  - [x] What we'll talk about and why we're doing it
  - Testing if gem5 boots linux
    - [x] Talk about downloading gem5, linux, etc.
    - [x] Show how to create all of the artifacts
    - [x] Show how to create a script to run everything
    - [x] Show what the output is
    - [x] Show how to search the DB to see what the results are

**Comment by powerjg** [comment]
@ayaz91: Please update this with `[x]` and `[ ]` for what has been done and what hasn't been done. Also, if the docs-stuff branch is stale, please remove it.

**Comment by aakahlow** [comment]
Outline updated and docs-stuff removed.

**Comment by powerjg** [comment]
Ping. Can you update this with the current status? If everything is done, let's close it!

**Comment by powerjg** [comment]
Ping again :)

**Comment by aakahlow** [comment]
I think, there are a couple of things left here. I will create a PR for the changes and close this afterward.
