### ISSUE TITLE
Add status information to gem5run objects

### ISSUE THREAD

**Issue by mahyarsamani** [darchr/gem5art#114]
Add member variable status to gem5rub objects that user can set in their simulation (most probably in their run script).

**Comment by powerjg** [comment]
This needs more details. Why is this needed? How does the run script know anything about gem5art? What would we change?

**Comment by powerjg** [comment]
To "signal" to the gem5art runner that the run failed, all you have to do is exit with a non-zero exit code. Is that not enough?

**Comment by powerjg** [comment]
@mahyarsamani, do you remember any more details on this? As it is, if we don't have more details we'll have to close this issue.

**Comment by mahyarsamani** [comment]
I think this was resolved by your comment on Oct 21. I'm closing this issue now.
