### ISSUE TITLE
Recursively Zipping the Results

### ISSUE THREAD

**Issue by hnpl** [darchr/gem5art#52]
Currently, saveResults() does not include files in subdirectories in result.zip. Also, when I unzip the file, it uses the absolute paths to structure the output folder. I think it's better to use relative paths.

**Comment by powerjg** [comment]
Seems important to me. Could you put this on Jira instead? 

Also, feel free to create the patch yourself :)

**Comment by hnpl** [comment]
Made the Jira issue.
