### ISSUE TITLE
Questions on Multi-programmed workload, System Emulation mode SPEC

### ISSUE THREAD

**Issue by AbhishekUoR** [darchr/gem5art#74]
Is gem5art going to release notes on how to run standard workloads like SPEC2k17 or SPEC2k6 using System Emulation mode? 
This is because Full System mode takes more time when compared to SE mode.
Also, the tool does not give instruction on running a Multi-programmed workload (Multi-core) using SE mode.
Will, there be near future support on it by this tool?

**Comment by powerjg** [comment]
We do not plan on adding any documentation on running SPEC or multiprogrammed workloads in SE mode. SE mode is not very appropriate for most systems research since it does not correctly model many important elements of system performance (e.g., page table walks, operating systems, etc.). There should be little difference in performance between SE mode and FS mode. You can use features like KVM fast-forwarding or checkpointing to avoid the time to boot linux.

**Comment by AbhishekUoR** [comment]
I agree about your argument on FS being better than SE when it comes to most systems research.
But most top conferences(ISCA, HPCA, ASPLOS, PACT, MICRO) accepts SE results and it would help a lot if gem5art does.
Also, as the tool supports FS so heavily, will there be the release of pre-built image and kernel which gem5 supplied and it has been outdated?
Instead of using docker and making images, a simple release of the image and kernel which are pre-tested would be the best.
As most people who do Computer Architecture research lies in EE department and not in CS, so learning docker is just creating hurdles instead of the way previous gem5 developers provided images and kernel

**Comment by aakahlow** [comment]
Hi, @AbhishekUoR : As far as updated disk image and kernel are concerned, look at the following post on gem5 mailing list to access them:

https://www.mail-archive.com/gem5-users@gem5.org/msg17274.html

You might have to update the root/.bashrc (inside that disk image) to make sure that system does not exit after linux boot-up. 

Also, the current status of working of different gem5 configurations with different linux kernels can be found at the bottom of the following tutorial:

https://gem5art.readthedocs.io/en/latest/tutorials/boot-tutorial.html

**Comment by powerjg** [comment]
> I agree about your argument on FS being better than SE when it comes to most systems research.
> But most top conferences(ISCA, HPCA, ASPLOS, PACT, MICRO) accepts SE results and it would help a lot if gem5art does.

Just because it's been accepted in the past doesn't mean it's good research. We need to educate our community on what is reasonable and what isn't in gem5 :).

**Comment by powerjg** [comment]
BTW, gem5art is open source. I would be happy to support SE mode more fully if you want to contribute that! It's unlikely that we will work on it here at UC Davis, though.

**Comment by AbhishekUoR** [comment]
Thanks, ayaz91 and powerjg for your help!
