### ISSUE TITLE
Assertion `!inParallelMode || this == curEventQueue()' fails for atomic cpu

### ISSUE THREAD

**Issue by mabdullahsoyturk** [darchr/gem5art#77]
When no_kvm option is enabled, linux boot fails for atomic cpu since memory mode should be atomic but even when I fix that Assertion `!inParallelMode || this == curEventQueue()' fails during the linux boot. 

Here is the related line: https://github.com/darchr/gem5art/blob/07584fd60d7f3de176a5f4f2c9bdd5bf4e51b2bf/docs/gem5-configs/configs-npb-tests/system/system.py#L121

**Comment by aakahlow** [comment]
Hi @mabdullahsoyturk: the condition on line 106 (which should be true by default) is leading to the error message you are seeing. Basically, multiple host cores can only be used if your cpu is kvm
